GET http://localhost:3001/todos HTTP/1.1

###

POST http://localhost:3001/todo/new 
Content-Type: application/json

{
"text": "Pick up boat"
}

###

DELETE http://localhost:3001/todo/delete/60e585eb6177f95ff0574326

###

GET http://localhost:3001/todo/complete/61ca915eac3d2570914d17fb

###

PUT http://localhost:3001/todo/update/61caa5fab7eb42a4f4443ce8
Content-Type: application/json

{
"text": "updated task"
}